# Generated by Django 6.0.6 on 2026-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology_stack', models.CharField(help_text='Comma-separated list of technologies (e.g. Python, Django, HTML)', max_length=250)),
                ('image', models.CharField(blank=True, help_text='Path or URL to project thumbnail image', max_length=500)),
                ('project_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
